// report generates REPORT.md from the businesses/<slug>/data.json research.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

type YearlyFigure struct {
	Year   int     `json:"year"`
	Amount float64 `json:"amount"`
}

type Business struct {
	Name             string         `json:"name"`
	Type             string         `json:"type"`
	Location         string         `json:"location"`
	URL              string         `json:"url"`
	AskingPrice      float64        `json:"asking_price"`
	Revenue          []YearlyFigure `json:"revenue"`
	SDE              []YearlyFigure `json:"sde"`
	Inventory        float64        `json:"inventory"`
	FFE              float64        `json:"ffe"`
	RealEstate       string         `json:"real_estate"`
	LeaseMonthly     float64        `json:"lease_monthly"`
	LeaseExpiresYear int            `json:"lease_expires_year"`
	YearsInBusiness  int            `json:"years_in_business"`
	Employees        int            `json:"employees"`
	ReasonForSelling string         `json:"reason_for_selling"`
	AIOpportunity    string         `json:"ai_opportunity"`
	Notes            string         `json:"notes"`
}

type Candidate struct {
	Slug string
	Path string
	Biz  Business
}

type ReportEntry struct {
	Candidate
	Metrics Metrics
	Score   Score
}

func main() {
	dir := flag.String("dir", "businesses", "root directory containing business sub-directories")
	out := flag.String("out", "REPORT.md", "report path to write")
	down := flag.Float64("down", 10.0, "down payment percentage")
	rate := flag.Float64("rate", 10.50, "SBA loan annual interest rate percentage")
	term := flag.Int("term", 10, "SBA loan term in years")
	flag.Parse()

	candidates, err := loadCandidates(*dir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "report: %v\n", err)
		os.Exit(1)
	}
	if len(candidates) == 0 {
		fmt.Fprintf(os.Stderr, "report: no businesses found in %q\n", *dir)
		os.Exit(1)
	}

	entries := make([]ReportEntry, 0, len(candidates))
	terms := Terms{
		DownPct:    *down / 100,
		AnnualRate: *rate / 100,
		TermYears:  *term,
	}
	for _, candidate := range candidates {
		metrics := ComputeMetrics(candidate.Biz, terms)
		score := ScoreBusiness(candidate.Biz, metrics)
		entries = append(entries, ReportEntry{
			Candidate: candidate,
			Metrics:   metrics,
			Score:     score,
		})
	}

	sort.Slice(entries, func(i, j int) bool {
		if entries[i].Score.Total == entries[j].Score.Total {
			return entries[i].Biz.Name < entries[j].Biz.Name
		}
		return entries[i].Score.Total > entries[j].Score.Total
	})

	report := renderReport(entries, terms)
	if err := os.WriteFile(*out, report, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "report: writing %s: %v\n", *out, err)
		os.Exit(1)
	}
	fmt.Printf("report: wrote %s with %d candidate(s)\n", *out, len(entries))
}

func loadCandidates(root string) ([]Candidate, error) {
	entries, err := os.ReadDir(root)
	if err != nil {
		return nil, fmt.Errorf("reading %s: %w", root, err)
	}

	var candidates []Candidate
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		slug := entry.Name()
		path := filepath.Join(root, slug, "data.json")
		data, err := os.ReadFile(path)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return nil, fmt.Errorf("reading %s: %w", path, err)
		}

		var biz Business
		if err := json.Unmarshal(data, &biz); err != nil {
			return nil, fmt.Errorf("parsing %s: %w", path, err)
		}
		candidates = append(candidates, Candidate{
			Slug: slug,
			Path: filepath.ToSlash(path),
			Biz:  biz,
		})
	}
	return candidates, nil
}

func renderReport(entries []ReportEntry, terms Terms) []byte {
	var b bytes.Buffer
	generated := time.Now().Format("2006-01-02")

	fmt.Fprintf(&b, "# Business Acquisition Research Report\n\n")
	fmt.Fprintf(&b, "Generated by `go run ./cmd/report` on %s.\n\n", generated)
	fmt.Fprintf(&b, "Scoring assumptions: %.0f%% down, %.2f%% annual interest, %d-year SBA term. Scores are heuristic research triage, not investment advice.\n\n",
		terms.DownPct*100, terms.AnnualRate*100, terms.TermYears)

	writeSummary(&b, entries)
	writeMethod(&b)
	writeDetails(&b, entries)

	return b.Bytes()
}

func writeSummary(b *bytes.Buffer, entries []ReportEntry) {
	fmt.Fprintf(b, "## Ranked Candidates\n\n")
	fmt.Fprintf(b, "| Rank | Score | Business | Location | Asking | SDE | DSCR | Multiple | Data | Why |\n")
	fmt.Fprintf(b, "|---:|---:|---|---|---:|---:|---:|---:|---:|---|\n")
	for i, entry := range entries {
		why := ""
		if len(entry.Score.Reasons) > 0 {
			why = entry.Score.Reasons[0]
		}
		fmt.Fprintf(b, "| %d | %.1f | [%s](%s) | %s | %s | %s | %s | %s | %.1f | %s |\n",
			i+1,
			entry.Score.Total,
			md(entry.Biz.Name),
			mdLink(entry.Path),
			md(entry.Biz.Location),
			usd(entry.Biz.AskingPrice),
			usd(entry.Metrics.LatestSDE),
			number(entry.Metrics.DSCR),
			multiple(entry.Metrics.SDEMultiple),
			entry.Score.DataConfidence,
			md(why),
		)
	}
	fmt.Fprintf(b, "\n")
}

func writeMethod(b *bytes.Buffer) {
	fmt.Fprintf(b, "## Scoring Model\n\n")
	fmt.Fprintf(b, "The quality score is capped at 100 points:\n\n")
	fmt.Fprintf(b, "- Financial quality: 30 points for DSCR, SDE multiple, margin, and payback.\n")
	fmt.Fprintf(b, "- AI/IT upside: 25 points for clear automation, software, data, routing, monitoring, CRM, or SaaS leverage.\n")
	fmt.Fprintf(b, "- Budget fit: 20 points for price/down-payment fit and SBA-prequalified signals.\n")
	fmt.Fprintf(b, "- Recurring and defensible revenue: 15 points for contracts, recurring revenue, essential services, route density, memberships, and operating history.\n")
	fmt.Fprintf(b, "- Data confidence: 10 points for known price, SDE, revenue, location, source URL, operating history, staffing, and asset/lease details.\n\n")
	fmt.Fprintf(b, "Candidates with missing SDE can still appear in the report, but they score poorly on financing quality until broker financials are collected.\n\n")
}

func writeDetails(b *bytes.Buffer, entries []ReportEntry) {
	fmt.Fprintf(b, "## Candidate Notes\n\n")
	for i, entry := range entries {
		biz := entry.Biz
		fmt.Fprintf(b, "### %d. %s - %.1f\n\n", i+1, biz.Name, entry.Score.Total)
		fmt.Fprintf(b, "- Slug: `%s`\n", entry.Slug)
		fmt.Fprintf(b, "- Type: %s\n", blank(biz.Type))
		fmt.Fprintf(b, "- Location: %s\n", blank(biz.Location))
		if biz.URL != "" {
			fmt.Fprintf(b, "- Source: <%s>\n", biz.URL)
		}
		fmt.Fprintf(b, "- Asking price: %s; down payment at 10%%: %s\n", usd(biz.AskingPrice), usd(entry.Metrics.DownPayment))
		fmt.Fprintf(b, "- Latest SDE: %s; latest revenue: %s; DSCR: %s; SDE multiple: %s\n",
			usd(entry.Metrics.LatestSDE),
			usd(entry.Metrics.LatestRevenue),
			number(entry.Metrics.DSCR),
			multiple(entry.Metrics.SDEMultiple),
		)
		fmt.Fprintf(b, "- Score breakdown: financial %.1f, AI/IT %.1f, budget %.1f, recurring %.1f, data %.1f\n",
			entry.Score.Financial,
			entry.Score.AIFit,
			entry.Score.Budget,
			entry.Score.Recurring,
			entry.Score.DataConfidence,
		)
		if len(entry.Score.Reasons) > 0 {
			fmt.Fprintf(b, "- Positive signals: %s\n", md(strings.Join(entry.Score.Reasons, "; ")))
		}
		if len(entry.Score.Warnings) > 0 {
			fmt.Fprintf(b, "- Open questions: %s\n", md(strings.Join(entry.Score.Warnings, "; ")))
		}
		if biz.AIOpportunity != "" {
			fmt.Fprintf(b, "- AI opportunity: %s\n", md(biz.AIOpportunity))
		}
		if biz.Notes != "" {
			fmt.Fprintf(b, "- Notes: %s\n", md(biz.Notes))
		}
		fmt.Fprintf(b, "\n")
	}
}

func usd(v float64) string {
	if v <= 0 {
		return "TBD"
	}
	s := fmt.Sprintf("%.0f", math.Round(v))
	n := len(s)
	out := make([]byte, 0, n+n/3)
	for i, c := range s {
		pos := n - i
		if i > 0 && pos%3 == 0 {
			out = append(out, ',')
		}
		out = append(out, byte(c))
	}
	return "$" + string(out)
}

func number(v float64) string {
	if v <= 0 {
		return "TBD"
	}
	return fmt.Sprintf("%.2f", v)
}

func multiple(v float64) string {
	if v <= 0 {
		return "TBD"
	}
	return fmt.Sprintf("%.2fx", v)
}

func blank(s string) string {
	if strings.TrimSpace(s) == "" {
		return "TBD"
	}
	return s
}

func md(s string) string {
	s = strings.ReplaceAll(s, "\r\n", " ")
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.ReplaceAll(s, "|", "\\|")
	return strings.TrimSpace(s)
}

func mdLink(s string) string {
	return strings.ReplaceAll(s, " ", "%20")
}
